# This workflow is triggered on push or pull request for the master branch.
# It verifies that the code is safe to merge.
---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GO_VERSION: "1.14"

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check goimports
        run: |
          go install golang.org/x/tools/cmd/goimports
          goimports -d cmd internal pkg

      - name: Check go mod
        run: |
          go mod tidy
          git diff

      - name: Check for license headers
        run: |
          go get -u github.com/google/addlicense
          addlicense -check cmd internal pkg

      - name: Run staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

      - name: Run tests
        run: |
          go test -v ./...

      - name: Check YAML
        uses: ibiqlik/action-yamllint@v3
